### ISSUE TITLE
Добавить признак перехода по ссылкам в нотифах

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/notify-service#17]
Добавить признак перехода по ссылкам в нотифах - для ивентов:
- лайка -редирект в пост, 
- дизлайка -редирект в пост, 
- ответа -релирект в комментарий, 
- упоминание -редирект в пост или комментарий, 
- подписка -редирект на профиль пользователя или активация подписки по кнопке.

**Comment by Format-X22** [comment]
Судя по всему задача для фронтенда, нужно в соответствующий репозиторий.

**Comment by Format-X22** [comment]
Реализовано в тикетах про fresh.
